from __future__ import annotations

import json
import sys
from pathlib import Path

import pandas as pd
import plotly.graph_objects as go
import streamlit as st

BASE_DIR = Path(__file__).resolve().parents[2]
MF_DIR = BASE_DIR / "data" / "processed" / "mf_comparison"

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))
import theme  # noqa: E402

st.set_page_config(page_title="Momentum Portfolio Dashboard — Funds", layout="wide", initial_sidebar_state="collapsed")
st.markdown(theme.PAGE_CSS, unsafe_allow_html=True)
st.markdown(
    '<div class="dash-header"><h1>Momentum Funds — Performance Comparison</h1>'
    '<p>Direct-growth plans · NAV data from api.mfapi.in · rebased to a common start so lines are directly comparable</p></div>',
    unsafe_allow_html=True,
)


def read_json_safe(path: Path) -> dict:
    if not path.exists():
        return {}
    with open(path, "r", encoding="utf-8") as f:
        return json.load(f)


metrics = read_json_safe(MF_DIR / "metrics.json")
rebased_path = MF_DIR / "rebased.csv"

if not metrics or metrics.get("status") != "ok" or not rebased_path.exists():
    st.info("Fund comparison data isn't available yet. It's generated by the daily update "
            "(scripts/cloud_rebuild.py / update_dashboard.py) — run one, then reload.", icon="ℹ️")
    st.stop()

funds = metrics["funds"]
# assign a fixed color per fund (validated categorical slots, in config order)
fund_names = list(funds.keys())
color_of = {name: theme.SERIES[i % len(theme.SERIES)] for i, name in enumerate(sorted(fund_names))}

st.markdown(
    f'<div class="stale-banner">Common window from {metrics["common_start"]} · '
    f'NAVs as of {metrics["as_of_date"]} · last computed {metrics.get("run_timestamp")}</div>',
    unsafe_allow_html=True,
)

# ── Rebased % return chart (common window) ───────────────────────────────────
st.markdown('<div class="section-title">Return Since Common Start (%)</div>', unsafe_allow_html=True)
st.caption(f"All funds rebased to 0% on {metrics['common_start']} (the newest fund's inception), "
           "so returns are compared over the same period.")

rebased = pd.read_csv(rebased_path, parse_dates=["Date"])
fig = go.Figure()
end_points = []
for name in rebased.columns:
    if name == "Date":
        continue
    series = rebased[["Date", name]].dropna()
    if series.empty:
        continue
    color = color_of.get(name, theme.PRIMARY_HUE)
    fig.add_trace(go.Scatter(
        x=series["Date"], y=series[name], name=name, mode="lines",
        line=dict(color=color, width=2),
        hovertemplate=f"<b>{name}</b> %{{x|%d %b %Y}}<br>%{{y:.1f}}%<extra></extra>",
    ))
    last = series.iloc[-1]
    fig.add_trace(go.Scatter(
        x=[last["Date"]], y=[last[name]], mode="markers",
        marker=dict(color=color, size=9, line=dict(color=theme.SURFACE, width=2)),
        showlegend=False, hoverinfo="skip",
    ))
    end_points.append((last[name], name, color, last["Date"]))

theme.styled_layout(fig, height=470, showlegend=True)
fig.update_yaxes(ticksuffix="%", zeroline=True, zerolinecolor=theme.AXIS, zerolinewidth=1)
# direct end-labels supplement the legend
for y, name, color, x_end in end_points:
    fig.add_annotation(x=x_end, y=y, text=f"  {y:+.1f}%", showarrow=False,
                       xanchor="left", font=dict(color=color, size=11), xshift=4)
fig.update_layout(margin=dict(l=8, r=60, t=8, b=8),
                  legend=dict(orientation="h", y=1.14, x=0, font=dict(color=theme.INK_SECONDARY)))
st.plotly_chart(fig, use_container_width=True)

# ── Metrics table ────────────────────────────────────────────────────────────
st.markdown('<div class="section-title">Fund Metrics</div>', unsafe_allow_html=True)
rows = []
for name, f in funds.items():
    rows.append({
        "Fund": name,
        "Type": f.get("category", ""),
        "Inception": f.get("inception"),
        "Latest NAV": f"{f['latest_nav']:.2f}",
        f"Return since {metrics['common_start']}": (f"{f['common_window_return']*100:+.1f}%"
                                                     if f.get("common_window_return") is not None else "—"),
        "Since inception": f"{f['since_inception_return']*100:+.1f}%",
        "CAGR": (f"{f['since_inception_cagr']*100:+.1f}%" if f.get("since_inception_cagr") is not None else "—"),
    })
mdf = pd.DataFrame(rows).sort_values(f"Return since {metrics['common_start']}", ascending=False)
st.dataframe(mdf, use_container_width=True, hide_index=True)

st.caption("Active = actively-managed momentum fund · Index = passive momentum index fund. "
           "Since-inception figures span different periods (funds launched on different dates) and "
           "are not directly comparable — use the common-window column for a like-for-like read. "
           "Past performance is not indicative of future results; this is data display, not advice.")
